#include <stdint.h>
#include <stm32l4xx.h>



void delay(unsigned int n){
	volatile unsigned int delay = n;
	while (delay--);
}

int main(void) {

	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOBEN;

	//7segmentjes
	GPIOB->MODER &= ~(GPIO_MODER_MODE0_Msk | GPIO_MODER_MODE7_Msk | GPIO_MODER_MODE5_Msk | GPIO_MODER_MODE12_Msk | GPIO_MODER_MODE15_Msk | GPIO_MODER_MODE1_Msk | GPIO_MODER_MODE2_Msk);
	GPIOB->MODER |= (GPIO_MODER_MODE0_0 | GPIO_MODER_MODE7_0 | GPIO_MODER_MODE5_0 | GPIO_MODER_MODE12_0 | GPIO_MODER_MODE15_0 | GPIO_MODER_MODE1_0 | GPIO_MODER_MODE2_0);
	GPIOB->OTYPER &= ~(GPIO_MODER_MODE0_0 | GPIO_MODER_MODE7_0 | GPIO_MODER_MODE5_0 | GPIO_MODER_MODE12_0 | GPIO_MODER_MODE15_0 | GPIO_MODER_MODE1_0 | GPIO_MODER_MODE2_0);

	//mux + punt
	GPIOA->MODER &= ~(GPIO_MODER_MODE8_Msk | GPIO_MODER_MODE15_Msk | GPIO_MODER_MODE6_Msk);
	GPIOA->MODER |= (GPIO_MODER_MODE8_Msk | GPIO_MODER_MODE15_Msk | GPIO_MODER_MODE6_Msk);
	GPIOA->OTYPER &= ~(GPIO_MODER_MODE8_Msk | GPIO_MODER_MODE15_Msk | GPIO_MODER_MODE6_Msk);



	while (1) {
		if (!(GPIOB->IDR  & GPIO_IDR_ID13)) {
			GPIOC->ODR |= GPIO_ODR_OD13;
			GPIOB->ODR |= GPIO_ODR_OD9;
			delay(500000);
			GPIOC->ODR &= ~GPIO_ODR_OD13;
			GPIOB->ODR &= ~GPIO_ODR_OD9;
			delay(500000);
		}

		else if (!(GPIOB->IDR & GPIO_IDR_ID14)){
			GPIOC->ODR |= GPIO_ODR_OD13;
			GPIOB->ODR |= GPIO_ODR_OD9;
			delay(2500000);
			GPIOC->ODR &= ~GPIO_ODR_OD13;
			GPIOB->ODR &= ~GPIO_ODR_OD9;
			delay(2500000);
			}

		else {
			GPIOC->ODR &= ~GPIO_ODR_OD13;
			GPIOB->ODR &= ~GPIO_ODR_OD9;
		}
	}


}
